# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Khoa Nguyen Blog"
description: > # this means to ignore newlines until "email:"
   Viết ngẫu hứng - Chủ yếu chuyện công nghệ

email: khoanguyen@khoanguyen.me
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Khoa Nguyen'
author: 'Khoa Nguyen'
author_image: "/assets/images/author.jpg"

paginate:	10

url: "http://thangngoc89.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/khoanguyenme
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/khoanguyen.me
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/thangngoc89
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
